create table users (
  id integer generated by default as identity primary key,
  is_administrator boolean not null default false,
  created_at text not null
);

create unique index users_single_administrator_idx
  on users (is_administrator)
  where is_administrator;

create table password_credentials (
  user_id integer primary key references users(id) on delete cascade,
  salt text not null,
  derived_key text not null,
  algorithm text not null check (algorithm = 'PBKDF2'),
  hash text not null check (hash = 'SHA-256'),
  iterations integer not null check (iterations = 600000),
  key_length_bits integer not null check (key_length_bits = 256),
  created_at text not null
);

create table browser_sessions (
  id text primary key,
  user_id integer references users(id) on delete cascade,
  data jsonb not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index browser_sessions_expires_at_idx on browser_sessions (expires_at);
create index browser_sessions_user_id_idx on browser_sessions (user_id);
