export const MAX_RUNNER_RPC_FRAME_BYTES = 1024 * 1024;
export const MAX_SESSION_GIT_PATH_CHARACTERS = 4_096;
export const MAX_SESSION_GIT_SNAPSHOT_FILES = 1_000;
export const MAX_SESSION_GIT_SNAPSHOT_FILES_JSON_BYTES = 192 * 1024;
export const MAX_SESSION_GIT_SNAPSHOT_PATCH_BYTES = 512 * 1024;
export const MAX_SESSION_GIT_SNAPSHOT_PATCH_JSON_BYTES = 384 * 1024;
export const MAX_SESSION_GIT_SNAPSHOT_PATCH_SECTION_BYTES = 256 * 1024;
export const MAX_SESSION_GIT_SNAPSHOT_PATCH_SECTION_JSON_BYTES = 220 * 1024;
