/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 6dbc85ed0b62210045fedada8aa7d48c)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	OPENORB_MASTER_KEY: string;
	SESSION_SECRET: string;
	PUBLIC_URL: string;
	OPENORB_SESSION_COOKIE_SECURE: string;
	WORKSPACE: DurableObjectNamespace<import("./dist/worker").Workspace>;
	RUNNERS: DurableObjectNamespace<import("./dist/worker").Runners>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/worker");
		durableNamespaces: "Workspace" | "Runners";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENORB_MASTER_KEY" | "SESSION_SECRET" | "PUBLIC_URL" | "OPENORB_SESSION_COOKIE_SECURE">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}